name: Update Postman Collection with Dynamic Authorization

on:
  push:
    paths:
      - "IntegracionPostmanGithub.postman_collection.json" # Activación al modificar este archivo

jobs:
  update-collection:
    runs-on: ubuntu-latest

    steps:
      # Clonar el repositorio
      - uses: actions/checkout@v4

      # Configurar Node.js para ejecutar el script
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14"

      # Instalar Axios para solicitudes HTTP
      - name: Install Axios
        run: npm install axios

      # Crear y ejecutar el script para actualizar la colección
      - name: Update Postman Collection with Authorization
        env:
          POSTMAN_API_KEY: ${{ secrets.POSTMAN_API_KEY }} # Secreto para la API de Postman
          API_KEY_GITHUB: ${{ secrets.API_KEY_GITHUB }}   # Secreto para el Authorization
        run: |
          echo 'const axios = require("axios");
          const fs = require("fs");

          const POSTMAN_API_KEY = process.env.POSTMAN_API_KEY;
          const API_KEY_GITHUB = process.env.API_KEY_GITHUB;
          const COLLECTION_UID = "3945000-f297e8c1-f208-4439-9ea1-be16e05a2a5a"; // UID de Postman
          const COLLECTION_FILE = "IntegracionPostmanGithub.postman_collection.json"; // Archivo JSON

          async function updateCollection() {
            try {
              // Leer el archivo JSON de la colección
              let collectionData = JSON.parse(fs.readFileSync(COLLECTION_FILE, "utf8"));

              // Reemplazar el valor del Authorization
              collectionData.item.forEach((item) => {
                if (item.request && item.request.header) {
                  item.request.header.forEach((header) => {
                    if (header.key.toLowerCase() === "authorization") {
                      header.value = `Bearer ${API_KEY_GITHUB}`;
                    }
                  });
                }
              });

              // Enviar la colección actualizada a Postman
              const response = await axios.put(
                `https://api.getpostman.com/collections/${COLLECTION_UID}`,
                { collection: collectionData },
                {
                  headers: {
                    "X-Api-Key": POSTMAN_API_KEY,
                    "Content-Type": "application/json",
                  },
                }
              );

              console.log("✅ Colección actualizada correctamente:", response.data);
            } catch (error) {
              console.error("❌ Error al actualizar la colección:", error.response?.data || error.message);
              process.exit(1);
            }
          }

          updateCollection();' > updateCollection.js
          node updateCollection.js
